### ISSUE TITLE
如何用于已经封装好的Map组件里

### ISSUE THREAD

**Issue by FreeTrea** [sakitam-fdd/ol-plot#14]
大佬你好，如题；我用的vue2，然后用的别人封装好的ol相关的Map组件，ol已经打包在组件里，然后组件无法修改，有暴露出map对象；我一开始直接引入ol-plot，然后把组件提供的map对象传入，结果报错“传入的不是地图对象！”，这种情况咋处理。望大佬能提点一二【抱拳】

**Comment by sakitam-fdd** [comment]
@FreeTrea 隐隐感觉是ol版本依赖的问题，就是项目里面打包进去了多个版本

**Comment by FreeTrea** [comment]
> 

是啊 和map组件不是同一个的ol，不知道咋解决了

**Comment by sakitam-fdd** [comment]
@FreeTrea 做一下依赖提升，强制为一个版本试下
