### ISSUE TITLE
请问是否考虑增加单个标绘删除功能？

### ISSUE THREAD

**Issue by wuxianshi** [sakitam-fdd/ol-plot#15]
plotDraw.activate()能否将feature对象返回，用于删除，亦或是直接返回删除方法

**Comment by sakitam-fdd** [comment]
@wuxianshi 没太理解，是想拿到绘制的要素吗，这个可以通过实例的 feature可以拿到，或者事件 `drawStart` 和 `drawEnd`都行

**Comment by wuxianshi** [comment]
@sakitam-fdd 已经通过plotDraw.feature获取到feature对象，非常感谢
