### ISSUE TITLE
颜色和透明度

### ISSUE THREAD

**Issue by Rexwang0410** [sakitam-fdd/ol-plot#18]
请问第一个example是否有开源的代码 请问怎么修改颜色 感谢

**Comment by sakitam-fdd** [comment]
@Rexwang0410 请查看 [示例源码](https://github.com/sakitam-fdd/ol-plot/tree/master/playground)，使用的面板组件源码在 [ol-plot-vue](https://github.com/sakitam-fdd/ol-plot/tree/master/packages/ol-plot-vue)
