### ISSUE TITLE
npm是否要更新下？

### ISSUE THREAD

**Issue by sys2007** [sakitam-fdd/ol-plot#2]
样列发现有些代码在npm中没有更新。如:
PlotTextBox类中
on(content, 'focus', this.handleFocus_.bind(this))    
on(content, 'blur', this.handleBlur_.bind(this))
这些事件。

**Comment by sakitam-fdd** [comment]
已经升级到 v2.1.3，但是没理解 `没有更新` 是什么意思

**Comment by sys2007** [comment]
更新后没问题了。我之前用的2.1.2版本。谢谢。

**Comment by sakitam-fdd** [comment]
不用客气 :smile:
