### ISSUE TITLE
画完图形后，某些图形缺少了可编辑点

### ISSUE THREAD

**Issue by bignose678** [sakitam-fdd/ol-plot#23]
![image](https://github.com/sakitam-fdd/ol-plot/assets/76949697/bebd2ce0-0a93-4da3-baff-a16eec2c6ddc)
图中，钳图，顶端两个可编辑点缺失。鼠标离开后，重新聚焦可编辑点能出来。

**Comment by sakitam-fdd** [comment]
@bignose678 你是说 [blog.sakitam.com/ol-plot/](https://blog.sakitam.com/ol-plot/) 这个地址的是吧，应该是这个位置有问题 https://github.com/sakitam-fdd/ol-plot/blob/9a2056112241b5331013f6290436d3492296f9dd/packages/ol-plot-vue/src/plot.vue#L476 

项目中使用的话需要判断是 plot 图形，并且未在绘制过程中再激活编辑

```js
 if (feature && feature.get("isPlot") && !this.plot.plotDraw.isDrawing()) {
    this.plot.plotEdit.activate(feature);
  } else {
    this.plot.plotEdit.deactivate();
  }
```

**Comment by sakitam-fdd** [comment]
fixed
