### ISSUE TITLE
Openlayers地图往右或者左多拖拽几次，经度超过了180

### ISSUE THREAD

**Issue by dyx9541** [sakitam-fdd/ol-plot#27]
Openlayers地图往右或者左多拖拽几次，经度超过了180了都，好像不会自动计算经纬度，然后导致绘制的经纬度都是180+的，

**Comment by sakitam-fdd** [comment]
@dyx9541 目前不会自动限制在 -180-180 ，ol现在支持跨世界的经纬度渲染，如果转换为 -180 - 180 图形会有问题。这个是碰到什么问题了吗？

**Comment by dyx9541** [comment]
1. 将地图向右拖拽多次，使世界地图循环出现很多次后
2. 标绘点
3. 标绘点不显示。

**Comment by dyx9541** [comment]
标绘矩形也只有黄色块：
![image](https://github.com/sakitam-fdd/ol-plot/assets/43093521/3bfd0186-d085-4e0e-9774-f9a2787ad1de)

**Comment by dyx9541** [comment]
https://stackoverflow.com/questions/67579223/getcoordinates-function-return-wrong-coordinates   
https://gis.stackexchange.com/questions/257509/ol-control-mouseposition-epsg4326-over-180-180-longitude-ol4
好像是ol自带的问题

**Comment by sakitam-fdd** [comment]
@dyx9541 这个本来就是预期结果，你绘制在哪个世界，经度范围就在哪个范围，不然你无法处理跨世界数据
![image](https://github.com/sakitam-fdd/ol-plot/assets/19517451/2c5a365b-6508-4b17-819e-a3cf45e316b9)

如果默认处理数据限制在-180-180，那么就会出现下面情况（本身绘制的是跨三个世界的一条线，再次拿数据渲染会变成同一个世界的三条线）

![image](https://github.com/sakitam-fdd/ol-plot/assets/19517451/1ec84fbc-7444-4869-8653-7bf1b76c8c29)

如果你必须要的数据是-180-180，那么应该限制跨世界渲染，并且限制 extent
