### ISSUE TITLE
绘制的线无法拖动移动位置

### ISSUE THREAD

**Issue by alaxury** [sakitam-fdd/ol-plot#31]
npm 安装的话， 线可以整体移动位置， 但鼠标的poiniter curser不是move。
如果是直接引入的dist里的js，  线会无法整体移动。 我用的master分支最新打包的dist测试的。

**Comment by sakitam-fdd** [comment]
@alaxury 请提供最小示例和使用版本（ol 版本和 ol-plot 版本），这里测试过是正常的 https://codepen.io/sakitam-fdd/full/BaMQwvN。
怀疑是不是未引入相关依赖的 css

**Comment by alaxury** [comment]
您好，
您说的是对的。&nbsp;&nbsp;
但我又发现个缺陷。
可以在这个上复现的
https://codepen.io/sakitam-fdd/full/BaMQwvN
先画一条折线， 拖动折线上的点，鼠标松开后，移动鼠标，点还在跟随鼠标移动。
【要多拖动几次点才会复现， 附件里有我录的视频， 我已经复现了好多次了， 我debugger 发现好像没走mouseup那， 但不明白为什么没走，不会修复这个bug】
请问你们可以修复下这个bug吗， 附件是视频









chenyang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sakitam-fdd/ol-plot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sakitam-fdd/ol-plot] 绘制的线无法拖动移动位置 (Issue #31)





 
@alaxury 请提供最小示例和使用版本（ol 版本和 ol-plot 版本），这里测试过是正常的 https://codepen.io/sakitam-fdd/full/BaMQwvN
