### ISSUE TITLE
文本标绘问题

### ISSUE THREAD

**Issue by caobaojin** [sakitam-fdd/ol-plot#32]
1、新绘制一个文本时，文本框无法正常失去焦点，导致标绘的其他图形不能被选中
2、再拖动文本框时，经常出现文本框随鼠标移动的情况，且无法取消
3、标绘的文本在地图导出为图片时不显示

版本：ol-v5.3.3  ol-plot-4.1.3

**Comment by sakitam-fdd** [comment]
@caobaojin 这有一个示例，似乎我这边复现不了 https://codepen.io/sakitam-fdd/full/BaMQwvN

**Comment by caobaojin** [comment]
> @caobaojin 这有一个示例，似乎我这边复现不了 https://codepen.io/sakitam-fdd/full/BaMQwvN

你先添加一个普通的图形，例如：进攻方向，然后再绘制文本，这个时候你选择刚才绘制的图形，看看是否能被选中，我试了一下你发的示例，出现了相同的问题

**Comment by sakitam-fdd** [comment]
fixed on ol-plot@4.1.6
