### ISSUE TITLE
import { Point as $Point } from 'ol/geom'   是不是不应该这么写啊  报错啊 引入后

### ISSUE THREAD

**Issue by lzp0070007** [sakitam-fdd/ol-plot#5]
![image](https://user-images.githubusercontent.com/5045130/56410824-26ba7c80-62b1-11e9-9695-abefc1a85dd3.png)

**Comment by sakitam-fdd** [comment]
@lzp0070007 升级一下 ol package 试下，用 5.3.0

**Comment by lzp0070007** [comment]
自己打包吗@sakitam-fdd

**Comment by sakitam-fdd** [comment]
@lzp0070007 项目的依赖， `ol-plot` 并没有把 `ol`打包进去，他依赖的是项目的 `ol`

**Comment by lzp0070007** [comment]
我的意思 是不是应该 这么定义啊 import {Point as $Point} from 'ol/geom/Point'

**Comment by lzp0070007** [comment]
谢谢了
