### ISSUE TITLE
请问为何v3版本中已绘制的图形不能编辑，仅能拖动？

### ISSUE THREAD

**Issue by josephvong** [sakitam-fdd/ol-plot#6]

**Comment by josephvong** [comment]
Q: in V3, feature which drawed and use in "plot.plotEdit(feature)", but fail to modify, only dragable.

**Comment by sakitam-fdd** [comment]
@josephvong 可以提供一个最小示例吗

**Comment by luluy** [comment]
我也遇到同样的问题了，这个要如何解决

**Comment by ANALKH-DY** [comment]
1.examples文件夹缺少ol-plot.css文件，通过npm 安装 里面有该css文件，解决控制点不显示的问题。
2.在vue3+ol6中，控制点overlay移除失败，考虑使用以下方式删除：
`if (item && item instanceof Overlay) {
          console.log('控制点',typeof item ,typeof _this3.map.getOverlayById(item.id));
          
          _this3.map.removeOverlay(_this3.map.getOverlayById(item.id));
        }`

**Comment by wuxianshi** [comment]
> 

请问一下是怎么在vue3+ol6中使用该库的，需要改动哪些东西或者进行什么操作呢？谢谢

**Comment by wuxianshi** [comment]
> 1.examples文件夹缺少ol-plot.css文件，通过npm 安装 里面有该css文件，解决控制点不显示的问题。 2.在vue3+ol6中，控制点overlay移除失败，考虑使用以下方式删除： `if (item && item instanceof Overlay) { console.log('控制点',typeof item ,typeof _this3.map.getOverlayById(item.id));
> 
> ```
>       _this3.map.removeOverlay(_this3.map.getOverlayById(item.id));
>     }`
> ```

请问一下是怎么在vue3+ol6中使用该库的，需要改动哪些东西或者进行什么操作呢？谢谢

**Comment by sakitam-fdd** [comment]
注意：编辑节点是 `ol.Overlay` , 是 dom 节点，`ol-plot` 中的 `ol-plot.css` 样式文件需要同步引入
